export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

import { NextResponse } from 'next/server';
import prisma from '@/lib/prisma';

function onlyDigits(s: string): string {
  return String(s || '').replace(/\D/g, '');
}

async function ensureManualColabTable() {
  await prisma.$executeRawUnsafe(`
    CREATE TABLE IF NOT EXISTS epi_manual_colab (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      cpf TEXT NOT NULL UNIQUE,
      matricula TEXT,
      nome TEXT,
      funcao TEXT,
      unidade TEXT,
      regional TEXT,
      admissao DATE,
      demissao DATE,
      created_at TIMESTAMPTZ DEFAULT now(),
      updated_at TIMESTAMPTZ DEFAULT now()
    );
  `);
}

export async function GET(req: Request) {
  try {
    const url = new URL(req.url);
    const raw = url.searchParams.get('cpf') || '';
    const cpf = onlyDigits(raw);
    return await handleLookup(cpf);
  } catch (e:any) {
    return NextResponse.json({ ok: false, exists: false, error: e?.message || String(e) }, { status: 200 });
  }
}

export async function POST(req: Request) {
  try {
    const body = await req.json().catch(() => ({}));
    const cpf = onlyDigits(String(body?.cpf || ''));
    return await handleLookup(cpf);
  } catch (e:any) {
    return NextResponse.json({ ok: false, exists: false, error: e?.message || String(e) }, { status: 200 });
  }
}

async function handleLookup(cpf: string) {
  if (!cpf) {
    return NextResponse.json({ ok: true, exists: false });
  }

  await ensureManualColabTable();

  // Preferir Alterdata (nome oficial), depois manual
  const sql = `
    select * from (
      select
        'alterdata'::text as source,
        coalesce(nullif(trim(nome), ''), null) as nome
      from mv_alterdata_flat
      where cpf = $1
      limit 1

      union all

      select
        'manual'::text as source,
        coalesce(nullif(trim(nome), ''), null) as nome
      from epi_manual_colab
      where cpf = $1
      limit 1
    ) s
    limit 1
  `;

  // @ts-ignore
  const rows: any[] = await prisma.$queryRawUnsafe(sql, cpf);
  if (!rows.length) {
    return NextResponse.json({ ok: true, exists: false });
  }

  return NextResponse.json({
    ok: true,
    exists: true,
    source: rows[0]?.source || null,
    nome: rows[0]?.nome || null,
  });
}
