export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

import { NextResponse } from 'next/server';
import prisma from '@/lib/prisma';
import { isEpiObrigatorio } from '@/data/epiObrigatorio';
import { findBestUnitMatch } from '@/lib/unitMatcher';
import { findBestFunctionMatch } from '@/lib/functionMatcher';

/**
 * Retorna dados de entregas por unidade hospitalar
 * Apenas quando há filtro de Regional
 */
export async function GET(req: Request) {
  try {
    const url = new URL(req.url);
    const regional = url.searchParams.get('regional') || '';
    const ano = parseInt(url.searchParams.get('ano') || '2026', 10);

    if (!regional) {
      return NextResponse.json({ 
        ok: false, 
        error: 'Regional é obrigatória para diagnóstico por unidade',
        unidades: []
      });
    }

    // Verifica se stg_unid_reg existe
    const hasUnidReg: any[] = await prisma.$queryRawUnsafe(`
      SELECT EXISTS (
        SELECT 1 FROM pg_catalog.pg_class c
        JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
        WHERE c.relkind IN ('r','v','m') AND n.nspname = 'public' AND c.relname = 'stg_unid_reg'
      ) AS exists
    `);
    const useJoin = hasUnidReg?.[0]?.exists;

    if (!useJoin) {
      return NextResponse.json({
        ok: false,
        error: 'Tabela stg_unid_reg não encontrada',
        unidades: []
      });
    }

    const regTrim = regional.trim();
    // Só considera cadastro ATIVO: demissão em branco (não conta pessoa já demitida)
    const DEMISSAO_WHERE = `(a.demissao IS NULL OR a.demissao = '' OR TRIM(a.demissao) = '')`;

    // Busca unidades da regional
    const unidadesSql = `
      SELECT DISTINCT
        COALESCE(NULLIF(TRIM(u.nmdepartamento), ''), NULLIF(TRIM(a.unidade_hospitalar), ''), '') AS unidade,
        COALESCE(NULLIF(TRIM(u.regional_responsavel), ''), '') AS regional
      FROM stg_alterdata_v2 a
      LEFT JOIN stg_unid_reg u ON UPPER(TRIM(COALESCE(a.unidade_hospitalar, ''))) = UPPER(TRIM(COALESCE(u.nmdepartamento, '')))
      WHERE (UPPER(TRIM(COALESCE(u.regional_responsavel, ''))) = UPPER(TRIM('${regTrim.replace(/'/g, "''")}')) 
             OR UPPER(TRIM(COALESCE(a.unidade_hospitalar, ''))) IN (
               SELECT UPPER(TRIM(nmdepartamento)) FROM stg_unid_reg WHERE UPPER(TRIM(regional_responsavel)) = UPPER(TRIM('${regTrim.replace(/'/g, "''")}'))
             ))
        AND ${DEMISSAO_WHERE}
      ORDER BY unidade ASC
    `;

    let unidadesRaw: any[] = [];
    try {
      unidadesRaw = await prisma.$queryRawUnsafe<any[]>(unidadesSql);
    } catch (sqlError) {
      console.error('Erro ao buscar unidades:', sqlError);
      return NextResponse.json({
        ok: false,
        error: `Erro ao buscar unidades: ${String(sqlError)}`,
        unidades: [],
      });
    }
    
    const unidadesList = Array.from(new Set(
      unidadesRaw.map((u: any) => String(u.unidade || '').trim()).filter(Boolean)
    ));
    
    if (unidadesList.length === 0) {
      return NextResponse.json({
        ok: true,
        unidades: [],
        ano,
        message: 'Nenhuma unidade encontrada para esta regional',
      });
    }

    // Busca kits de stg_epi_map (mesma fonte do botão "Entregar") - NOVA ESTRUTURA
    let kitRows: any[] = [];
    try {
      kitRows = await prisma.$queryRawUnsafe<any[]>(`
        SELECT
          COALESCE(pcg, '') AS pcg,
          COALESCE(alterdata_funcao, '') AS funcao,
          COALESCE(funcao_normalizada, alterdata_funcao, '') AS funcao_norm,
          COALESCE(unidade_hospitalar, '') AS unidade_hosp,
          COALESCE(epi_item, '') AS item,
          COALESCE(quantidade::numeric, 1) AS qtd
        FROM stg_epi_map
      `);
      console.log(`[Diagnóstico] Kits encontrados em stg_epi_map: ${kitRows.length}`);
    } catch (mapError: any) {
      console.error('[Diagnóstico] Erro ao buscar de stg_epi_map:', mapError?.message || mapError);
      return NextResponse.json({
        ok: false,
        error: `Erro ao buscar kits: ${String(mapError)}`,
        unidades: [],
      });
    }

    // Busca todas as funções do mapa para comparar (cache de funções)
    let allFunctionsList: string[] = [];
    try {
      const allFuncs = await prisma.$queryRawUnsafe<any[]>(`
        SELECT DISTINCT alterdata_funcao FROM stg_epi_map WHERE alterdata_funcao IS NOT NULL
      `);
      allFunctionsList = allFuncs.map(f => f.alterdata_funcao);
    } catch (e) {
      console.warn('[Diagnóstico] Erro ao carregar lista de funções:', e);
    }

    // Garante tabela de entregas
    await prisma.$executeRawUnsafe(`
      CREATE TABLE IF NOT EXISTS epi_entregas (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        cpf TEXT NOT NULL,
        item TEXT NOT NULL,
        qty_required INT DEFAULT 1,
        qty_delivered INT DEFAULT 0,
        deliveries JSONB DEFAULT '[]',
        created_at TIMESTAMPTZ DEFAULT now(),
        updated_at TIMESTAMPTZ DEFAULT now(),
        UNIQUE(cpf, item)
      );
    `);

    // Busca todas as entregas de uma vez (otimização de performance)
    const todasEntregas = await prisma.$queryRawUnsafe<any[]>(`
      SELECT cpf, item, deliveries
      FROM epi_entregas
    `).catch(() => []);

    // Para cada unidade, calcula meta e entregas por mês
    const unidades: Array<{
      unidade: string;
      qtePrevista: number;
      meses: Record<string, number>;
      totalRealizada: number;
    }> = [];

    for (const unidadeNome of unidadesList) {
      // Busca CPFs da unidade
      const cpfsSql = `
        SELECT DISTINCT COALESCE(a.cpf, '') AS cpf
        FROM stg_alterdata_v2 a
        LEFT JOIN stg_unid_reg u ON UPPER(TRIM(COALESCE(a.unidade_hospitalar, ''))) = UPPER(TRIM(COALESCE(u.nmdepartamento, '')))
        WHERE (UPPER(TRIM(COALESCE(u.nmdepartamento, a.unidade_hospitalar, ''))) = UPPER(TRIM('${unidadeNome.replace(/'/g, "''")}')) 
               OR UPPER(TRIM(a.unidade_hospitalar)) = UPPER(TRIM('${unidadeNome.replace(/'/g, "''")}')))
          AND ${DEMISSAO_WHERE}
      `;

      let cpfsRaw: any[] = [];
      try {
        cpfsRaw = await prisma.$queryRawUnsafe<any[]>(cpfsSql);
      } catch (cpfError) {
        console.error(`Erro ao buscar CPFs da unidade ${unidadeNome}:`, cpfError);
        continue; // Pula esta unidade se der erro
      }
      
      const cpfs = cpfsRaw.map((c: any) => String(c.cpf || '').replace(/\D/g, '').slice(-11)).filter(Boolean);

      if (cpfs.length === 0) continue;

      // Calcula meta (Qte Prevista) - soma de EPIs obrigatórios
      // IMPORTANTE: NÃO agrupa por CPF - se CPF aparece 2x (demitido e voltou em 2026), conta 2x
      let qtePrevista = 0;
      
      // Busca TODOS os colaboradores da unidade (sem GROUP BY - mantém duplicatas se houver)
      const colaboradoresSql = `
        SELECT 
          COALESCE(a.cpf, '') AS cpf,
          COALESCE(a.funcao, '') AS funcao,
          COALESCE(a.unidade_hospitalar, '') AS unidade_hospitalar
        FROM stg_alterdata_v2 a
        LEFT JOIN stg_unid_reg u ON UPPER(TRIM(COALESCE(a.unidade_hospitalar, ''))) = UPPER(TRIM(COALESCE(u.nmdepartamento, '')))
        WHERE (UPPER(TRIM(COALESCE(u.nmdepartamento, a.unidade_hospitalar, ''))) = UPPER(TRIM('${unidadeNome.replace(/'/g, "''")}')) 
               OR UPPER(TRIM(a.unidade_hospitalar)) = UPPER(TRIM('${unidadeNome.replace(/'/g, "''")}')))
          AND ${DEMISSAO_WHERE}
          AND COALESCE(a.cpf, '') != ''
          AND COALESCE(a.funcao, '') != ''
      `;
      
      let colaboradores: any[] = [];
      try {
        colaboradores = await prisma.$queryRawUnsafe<any[]>(colaboradoresSql);
      } catch (err) {
        console.error(`Erro ao buscar colaboradores da unidade ${unidadeNome}:`, err);
      }
      
      // Funções auxiliares (mesmas do /api/entregas/kit)
      function normKey(s: any): string {
        return (s ?? '').toString().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]/gi, '').toLowerCase();
      }
      
      function normFuncKey(s: any): string {
        const raw = (s ?? '').toString();
        const cleaned = raw.replace(/\(A\)/gi, '').replace(/\s+/g, ' ');
        return normKey(cleaned);
      }
      
      function normUnidKey(s: any): string {
        const raw = (s ?? '').toString().normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase();
        const withoutStops = raw.replace(/\b(hospital|hosp|de|da|das|do|dos)\b/g, ' ');
        return withoutStops.replace(/[^a-z0-9]/gi, '');
      }
      
      // Cache de kits por função+unidade (para performance)
      const kitCache = new Map<string, number>(); // chave: "funcaoKey" -> soma de itens obrigatórios (kit-base sem setor)

      const isSemSetorBase = (s: any) => {
        const v = String(s ?? '')
          .normalize('NFD')
          .replace(/[\u0300-\u036f]/g, '')
          .toUpperCase()
          .replace(/\s+/g, ' ')
          .trim();
        return v.includes('SEM SETOR');
      };
      const isPcgUniversal = (s: any) => {
        const v = String(s ?? '')
          .normalize('NFD')
          .replace(/[\u0300-\u036f]/g, '')
          .toUpperCase()
          .replace(/\s+/g, ' ')
          .trim();
        return v.includes('PCG UNIVERSAL');
      };

      // Busca todas as unidades do mapa para comparar
      let allUnitsList: string[] = [];
      try {
        const allUnits = await prisma.$queryRawUnsafe<any[]>(`
          SELECT DISTINCT unidade_hospitalar FROM stg_epi_map 
          WHERE unidade_hospitalar IS NOT NULL 
            AND TRIM(unidade_hospitalar) != ''
            AND unidade_hospitalar != 'PCG UNIVERSAL'
            AND unidade_hospitalar != 'SEM MAPEAMENTO NO PCG'
        `);
        allUnitsList = allUnits.map(u => u.unidade_hospitalar).filter(Boolean);
      } catch (e) {
        console.warn('[Diagnóstico] Erro ao carregar lista de unidades:', e);
      }
      
      // Para cada colaborador (mesmo CPF pode aparecer 2x)
      for (const colab of colaboradores) {
        const funcao = String(colab.funcao || '').trim();
        const unidadeHosp = String(colab.unidade_hospitalar || '').trim();
        
        if (!funcao) continue;
        
        const funcKey = normFuncKey(funcao);
        const unidadeKey = normUnidKey(unidadeHosp);
        
        // Resolve a melhor função usando Matcher Inteligente (Alias, Motorista, etc)
        let finalFuncKey = funcKey;
        let targetFuncName = funcao;
        if (allFunctionsList.length > 0) {
          const matchedFunc = findBestFunctionMatch(funcao, allFunctionsList);
          if (matchedFunc) {
            targetFuncName = matchedFunc;
            finalFuncKey = normFuncKey(matchedFunc);
          }
        }
        
        const cacheKey = `${finalFuncKey}`;
        
        // Busca soma do kit (usa cache)
        let somaKit = 0;
        if (kitCache.has(cacheKey)) {
          somaKit = kitCache.get(cacheKey)!;
        } else {
          // Kit-base (setor desconhecido):
          // - prioridade: PCG UNIVERSAL + "SEM SETOR ESPECÍFICO"
          // - fallback: PCG UNIVERSAL em QUALQUER setor (pega o maior por item)
          const semSetorRows: any[] = [];
          const anySetorRows: any[] = [];

          for (const r of kitRows) {
            const rFuncNorm = normFuncKey(r.funcao_norm || r.funcao);
            const rFuncAlt = normFuncKey(r.funcao);
            const funcMatch =
              (rFuncNorm && rFuncNorm === finalFuncKey) ||
              (rFuncAlt && rFuncAlt === finalFuncKey);
            if (!funcMatch) continue;

            const item = String(r.item || '').trim();
            if (!item || item.toUpperCase() === 'SEM EPI' || !isEpiObrigatorio(item)) continue;
            if (!isPcgUniversal(r.pcg)) continue;

            if (isSemSetorBase(r.unidade_hosp)) semSetorRows.push(r);
            anySetorRows.push(r);
          }

          const baseRows = semSetorRows.length > 0 ? semSetorRows : anySetorRows;
          const byItem = new Map<string, number>();
          for (const r of baseRows) {
            const item = String(r.item || '').trim();
            if (!item) continue;
            const qtd = Number(r.qtd || 1) || 1;
            if (qtd <= 0) continue;
            const itemKey = normKey(item);
            const existing = byItem.get(itemKey);
            if (!existing || qtd > existing) byItem.set(itemKey, qtd);
          }

          somaKit = Array.from(byItem.values()).reduce((acc, qtd) => acc + qtd, 0);
          kitCache.set(cacheKey, somaKit);
        }
        
        // Adiciona à meta (conta cada linha, mesmo se CPF duplicado)
        qtePrevista += somaKit;
      }
      
      console.log(`[Diagnóstico] Unidade ${unidadeNome}: ${colaboradores.length} colaboradores (pode ter CPFs duplicados), meta = ${qtePrevista} itens`);

      // Filtra entregas da unidade (já carregadas acima)
      const entregas = todasEntregas.filter((e: any) => {
        const eCpf = String(e.cpf || '').replace(/\D/g, '').slice(-11);
        return cpfs.includes(eCpf);
      });

      // Inicializa meses
      const meses: Record<string, number> = {};
      for (let m = 1; m <= 12; m++) {
        meses[String(m).padStart(2, '0')] = 0;
      }

      // Processa entregas por mês (apenas obrigatórios)
      // IMPORTANTE: Soma apenas EPIs obrigatórios entregues, baseado no campo deliveries JSONB
      for (const entrega of entregas) {
        const item = String(entrega.item || '').trim();
        if (!item || !isEpiObrigatorio(item)) continue; // Apenas obrigatórios contam

        const deliveries = Array.isArray(entrega.deliveries) ? entrega.deliveries : [];
        
        for (const del of deliveries) {
          if (!del.date || !del.qty) continue;
          
          const dateStr = String(del.date).substring(0, 10);
          const [year, month] = dateStr.split('-');
          
          // Valida formato de data
          if (!year || !month || year.length !== 4 || month.length !== 2) continue;
          
          if (parseInt(year, 10) === ano) {
            const mesKey = month.padStart(2, '0');
            const qty = Number(del.qty || 0);
            if (qty > 0) {
              meses[mesKey] = (meses[mesKey] || 0) + qty;
            }
          }
        }
      }

      const totalRealizada = Object.values(meses).reduce((acc, val) => acc + val, 0);

      unidades.push({
        unidade: unidadeNome,
        qtePrevista,
        meses,
        totalRealizada,
      });
    }

    // Ordena por nome da unidade
    unidades.sort((a, b) => a.unidade.localeCompare(b.unidade));

    return NextResponse.json({
      ok: true,
      unidades,
      ano,
    });
  } catch (e: any) {
    console.error('Erro ao calcular diagnóstico por unidade:', e);
    return NextResponse.json({
      ok: false,
      error: String(e?.message || e),
      unidades: [],
    });
  }
}
