export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

import { NextResponse } from 'next/server';
import prisma from '@/lib/prisma';
import { isEpiObrigatorio } from '@/data/epiObrigatorio';

/**
 * Retorna dados de entregas por unidade hospitalar
 * Apenas quando há filtro de Regional
 */
export async function GET(req: Request) {
  try {
    const url = new URL(req.url);
    const regional = url.searchParams.get('regional') || '';
    const ano = parseInt(url.searchParams.get('ano') || '2026', 10);

    if (!regional) {
      return NextResponse.json({ 
        ok: false, 
        error: 'Regional é obrigatória para diagnóstico por unidade',
        unidades: []
      });
    }

    // Verifica se stg_unid_reg existe
    const hasUnidReg: any[] = await prisma.$queryRawUnsafe(`
      SELECT EXISTS (
        SELECT 1 FROM pg_catalog.pg_class c
        JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
        WHERE c.relkind IN ('r','v','m') AND n.nspname = 'public' AND c.relname = 'stg_unid_reg'
      ) AS exists
    `);
    const useJoin = hasUnidReg?.[0]?.exists;

    if (!useJoin) {
      return NextResponse.json({
        ok: false,
        error: 'Tabela stg_unid_reg não encontrada',
        unidades: []
      });
    }

    const regTrim = regional.trim();
    const DEMISSAO_LIMITE = '2026-01-01';

    // Busca unidades da regional
    const unidadesSql = `
      SELECT DISTINCT
        COALESCE(NULLIF(TRIM(u.nmdepartamento), ''), NULLIF(TRIM(a.unidade_hospitalar), ''), '') AS unidade,
        COALESCE(NULLIF(TRIM(u.regional_responsavel), ''), '') AS regional
      FROM stg_alterdata_v2 a
      LEFT JOIN stg_unid_reg u ON UPPER(TRIM(COALESCE(a.unidade_hospitalar, ''))) = UPPER(TRIM(COALESCE(u.nmdepartamento, '')))
      WHERE (UPPER(TRIM(COALESCE(u.regional_responsavel, ''))) = UPPER(TRIM('${regTrim.replace(/'/g, "''")}')) 
             OR UPPER(TRIM(COALESCE(a.unidade_hospitalar, ''))) IN (
               SELECT UPPER(TRIM(nmdepartamento)) FROM stg_unid_reg WHERE UPPER(TRIM(regional_responsavel)) = UPPER(TRIM('${regTrim.replace(/'/g, "''")}'))
             ))
        AND (a.demissao IS NULL OR a.demissao = '' OR TRIM(a.demissao) = '' OR a.demissao::text >= '${DEMISSAO_LIMITE}')
      ORDER BY unidade ASC
    `;

    let unidadesRaw: any[] = [];
    try {
      unidadesRaw = await prisma.$queryRawUnsafe<any[]>(unidadesSql);
    } catch (sqlError) {
      console.error('Erro ao buscar unidades:', sqlError);
      return NextResponse.json({
        ok: false,
        error: `Erro ao buscar unidades: ${String(sqlError)}`,
        unidades: [],
      });
    }
    
    const unidadesList = Array.from(new Set(
      unidadesRaw.map((u: any) => String(u.unidade || '').trim()).filter(Boolean)
    ));
    
    if (unidadesList.length === 0) {
      return NextResponse.json({
        ok: true,
        unidades: [],
        ano,
        message: 'Nenhuma unidade encontrada para esta regional',
      });
    }

    // Busca kits esperados (apenas obrigatórios)
    let kitRows: any[] = [];
    try {
      // Tenta buscar de stg_epi_map primeiro (mais confiável)
      try {
        kitRows = await prisma.$queryRawUnsafe<any[]>(`
          SELECT
            COALESCE(alterdata_funcao::text, '') AS funcao,
            COALESCE(epi_item::text, '') AS item,
            COALESCE(quantidade::numeric, 0) AS qtd
          FROM stg_epi_map
        `);
        console.log(`[Diagnóstico] Kits encontrados em stg_epi_map: ${kitRows.length}`);
      } catch (mapError: any) {
        console.error('[Diagnóstico] Erro ao buscar de stg_epi_map:', mapError?.message || mapError);
        // Fallback para view
        kitRows = await prisma.$queryRaw<any[]>`
          SELECT
            COALESCE(cpf::text, '') AS cpf,
            COALESCE(epi_nome::text, '') AS item,
            COALESCE(quantidade::numeric, 0) AS qtd
          FROM vw_entregas_epi_unidade
        `;
        console.log(`[Diagnóstico] Kits encontrados na view: ${kitRows.length}`);
      }
    } catch (kitError) {
      console.error('[Diagnóstico] Erro ao buscar kits:', kitError);
      // Continua sem kits, mas vai retornar qtePrevista = 0
    }

    // Garante tabela de entregas
    await prisma.$executeRawUnsafe(`
      CREATE TABLE IF NOT EXISTS epi_entregas (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        cpf TEXT NOT NULL,
        item TEXT NOT NULL,
        qty_required INT DEFAULT 1,
        qty_delivered INT DEFAULT 0,
        deliveries JSONB DEFAULT '[]',
        created_at TIMESTAMPTZ DEFAULT now(),
        updated_at TIMESTAMPTZ DEFAULT now(),
        UNIQUE(cpf, item)
      );
    `);

    // Busca todas as entregas de uma vez (otimização de performance)
    const todasEntregas = await prisma.$queryRawUnsafe<any[]>(`
      SELECT cpf, item, deliveries
      FROM epi_entregas
    `).catch(() => []);

    // Para cada unidade, calcula meta e entregas por mês
    const unidades: Array<{
      unidade: string;
      qtePrevista: number;
      meses: Record<string, number>;
      totalRealizada: number;
    }> = [];

    for (const unidadeNome of unidadesList) {
      // Busca CPFs da unidade
      const cpfsSql = `
        SELECT DISTINCT COALESCE(a.cpf, '') AS cpf
        FROM stg_alterdata_v2 a
        LEFT JOIN stg_unid_reg u ON UPPER(TRIM(COALESCE(a.unidade_hospitalar, ''))) = UPPER(TRIM(COALESCE(u.nmdepartamento, '')))
        WHERE (UPPER(TRIM(COALESCE(u.nmdepartamento, a.unidade_hospitalar, ''))) = UPPER(TRIM('${unidadeNome.replace(/'/g, "''")}')) 
               OR UPPER(TRIM(a.unidade_hospitalar)) = UPPER(TRIM('${unidadeNome.replace(/'/g, "''")}')))
          AND (a.demissao IS NULL OR a.demissao = '' OR TRIM(a.demissao) = '' OR a.demissao::text >= '${DEMISSAO_LIMITE}')
      `;

      let cpfsRaw: any[] = [];
      try {
        cpfsRaw = await prisma.$queryRawUnsafe<any[]>(cpfsSql);
      } catch (cpfError) {
        console.error(`Erro ao buscar CPFs da unidade ${unidadeNome}:`, cpfError);
        continue; // Pula esta unidade se der erro
      }
      
      const cpfs = cpfsRaw.map((c: any) => String(c.cpf || '').replace(/\D/g, '').slice(-11)).filter(Boolean);

      if (cpfs.length === 0) continue;

      // Calcula meta (Qte Prevista) - soma de EPIs obrigatórios
      // IMPORTANTE: Soma apenas uma vez por colaborador único (por CPF), não duplica
      let qtePrevista = 0;
      const cpfsProcessados = new Set<string>();
      
      // Busca função dos colaboradores da unidade (agrupa por CPF para evitar duplicatas)
      const cpfsComFuncaoSql = `
        SELECT 
          COALESCE(a.cpf, '') AS cpf,
          MAX(COALESCE(a.funcao, '')) AS funcao
        FROM stg_alterdata_v2 a
        LEFT JOIN stg_unid_reg u ON UPPER(TRIM(COALESCE(a.unidade_hospitalar, ''))) = UPPER(TRIM(COALESCE(u.nmdepartamento, '')))
        WHERE (UPPER(TRIM(COALESCE(u.nmdepartamento, a.unidade_hospitalar, ''))) = UPPER(TRIM('${unidadeNome.replace(/'/g, "''")}')) 
               OR UPPER(TRIM(a.unidade_hospitalar)) = UPPER(TRIM('${unidadeNome.replace(/'/g, "''")}')))
          AND (a.demissao IS NULL OR a.demissao = '' OR TRIM(a.demissao) = '' OR a.demissao::text >= '${DEMISSAO_LIMITE}')
          AND COALESCE(a.cpf, '') != ''
        GROUP BY COALESCE(a.cpf, '')
      `;
      
      let cpfsComFuncao: any[] = [];
      try {
        cpfsComFuncao = await prisma.$queryRawUnsafe<any[]>(cpfsComFuncaoSql);
      } catch (err) {
        console.error(`Erro ao buscar CPFs com função da unidade ${unidadeNome}:`, err);
      }
      
      // Mapa de função -> kit (para evitar buscar múltiplas vezes)
      const kitPorFuncao = new Map<string, number>(); // Armazena soma total do kit da função
      
      for (const colab of cpfsComFuncao) {
        const cpf = String(colab.cpf || '').replace(/\D/g, '').slice(-11);
        const funcao = String(colab.funcao || '').trim();
        
        // Evita processar o mesmo CPF duas vezes (garantia extra)
        if (cpf && cpfsProcessados.has(cpf)) {
          console.log(`[Diagnóstico] CPF duplicado ignorado: ${cpf}`);
          continue;
        }
        if (cpf) cpfsProcessados.add(cpf);
        
        if (!funcao) continue;

        // Busca soma do kit da função (cache)
        let somaKitFuncao = 0;
        if (kitPorFuncao.has(funcao)) {
          somaKitFuncao = kitPorFuncao.get(funcao)!;
        } else {
          // Busca kit do colaborador (por função) e soma
          const kitColab = kitRows
            .filter((r: any) => {
              const item = String(r.item || '').trim();
              if (!item || !isEpiObrigatorio(item)) return false;
              
              const rFuncao = String(r.funcao || '').trim();
              return rFuncao === funcao;
            });
          
          // Soma quantidade de EPIs obrigatórios do kit da função
          somaKitFuncao = kitColab.reduce((acc, r) => acc + Number(r.qtd || 0), 0);
          kitPorFuncao.set(funcao, somaKitFuncao);
        }
        
        // Soma o kit completo do colaborador (uma vez por CPF)
        qtePrevista += somaKitFuncao;
      }
      
      console.log(`[Diagnóstico] Unidade ${unidadeNome}: ${cpfsProcessados.size} colaboradores únicos, meta = ${qtePrevista}`);

      // Filtra entregas da unidade (já carregadas acima)
      const entregas = todasEntregas.filter((e: any) => {
        const eCpf = String(e.cpf || '').replace(/\D/g, '').slice(-11);
        return cpfs.includes(eCpf);
      });

      // Inicializa meses
      const meses: Record<string, number> = {};
      for (let m = 1; m <= 12; m++) {
        meses[String(m).padStart(2, '0')] = 0;
      }

      // Processa entregas por mês (apenas obrigatórios)
      // IMPORTANTE: Soma apenas EPIs obrigatórios entregues, baseado no campo deliveries JSONB
      for (const entrega of entregas) {
        const item = String(entrega.item || '').trim();
        if (!item || !isEpiObrigatorio(item)) continue; // Apenas obrigatórios contam

        const deliveries = Array.isArray(entrega.deliveries) ? entrega.deliveries : [];
        
        for (const del of deliveries) {
          if (!del.date || !del.qty) continue;
          
          const dateStr = String(del.date).substring(0, 10);
          const [year, month] = dateStr.split('-');
          
          // Valida formato de data
          if (!year || !month || year.length !== 4 || month.length !== 2) continue;
          
          if (parseInt(year, 10) === ano) {
            const mesKey = month.padStart(2, '0');
            const qty = Number(del.qty || 0);
            if (qty > 0) {
              meses[mesKey] = (meses[mesKey] || 0) + qty;
            }
          }
        }
      }

      const totalRealizada = Object.values(meses).reduce((acc, val) => acc + val, 0);

      unidades.push({
        unidade: unidadeNome,
        qtePrevista,
        meses,
        totalRealizada,
      });
    }

    // Ordena por nome da unidade
    unidades.sort((a, b) => a.unidade.localeCompare(b.unidade));

    return NextResponse.json({
      ok: true,
      unidades,
      ano,
    });
  } catch (e: any) {
    console.error('Erro ao calcular diagnóstico por unidade:', e);
    return NextResponse.json({
      ok: false,
      error: String(e?.message || e),
      unidades: [],
    });
  }
}
