export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

import { NextResponse } from 'next/server';
import prisma from '@/lib/prisma';
import { isEpiObrigatorio } from '@/data/epiObrigatorio';
import { findBestUnitMatch } from '@/lib/unitMatcher';

/**
 * Retorna dados de entregas por unidade hospitalar
 * Apenas quando há filtro de Regional
 */
export async function GET(req: Request) {
  try {
    const url = new URL(req.url);
    const regional = url.searchParams.get('regional') || '';
    const ano = parseInt(url.searchParams.get('ano') || '2026', 10);

    if (!regional) {
      return NextResponse.json({ 
        ok: false, 
        error: 'Regional é obrigatória para diagnóstico por unidade',
        unidades: []
      });
    }

    // Verifica se stg_unid_reg existe
    const hasUnidReg: any[] = await prisma.$queryRawUnsafe(`
      SELECT EXISTS (
        SELECT 1 FROM pg_catalog.pg_class c
        JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
        WHERE c.relkind IN ('r','v','m') AND n.nspname = 'public' AND c.relname = 'stg_unid_reg'
      ) AS exists
    `);
    const useJoin = hasUnidReg?.[0]?.exists;

    if (!useJoin) {
      return NextResponse.json({
        ok: false,
        error: 'Tabela stg_unid_reg não encontrada',
        unidades: []
      });
    }

    const regTrim = regional.trim();
    const DEMISSAO_LIMITE = '2026-01-01';

    // Busca unidades da regional
    const unidadesSql = `
      SELECT DISTINCT
        COALESCE(NULLIF(TRIM(u.nmdepartamento), ''), NULLIF(TRIM(a.unidade_hospitalar), ''), '') AS unidade,
        COALESCE(NULLIF(TRIM(u.regional_responsavel), ''), '') AS regional
      FROM stg_alterdata_v2 a
      LEFT JOIN stg_unid_reg u ON UPPER(TRIM(COALESCE(a.unidade_hospitalar, ''))) = UPPER(TRIM(COALESCE(u.nmdepartamento, '')))
      WHERE (UPPER(TRIM(COALESCE(u.regional_responsavel, ''))) = UPPER(TRIM('${regTrim.replace(/'/g, "''")}')) 
             OR UPPER(TRIM(COALESCE(a.unidade_hospitalar, ''))) IN (
               SELECT UPPER(TRIM(nmdepartamento)) FROM stg_unid_reg WHERE UPPER(TRIM(regional_responsavel)) = UPPER(TRIM('${regTrim.replace(/'/g, "''")}'))
             ))
        AND (a.demissao IS NULL OR a.demissao = '' OR TRIM(a.demissao) = '' OR a.demissao::text >= '${DEMISSAO_LIMITE}')
      ORDER BY unidade ASC
    `;

    let unidadesRaw: any[] = [];
    try {
      unidadesRaw = await prisma.$queryRawUnsafe<any[]>(unidadesSql);
    } catch (sqlError) {
      console.error('Erro ao buscar unidades:', sqlError);
      return NextResponse.json({
        ok: false,
        error: `Erro ao buscar unidades: ${String(sqlError)}`,
        unidades: [],
      });
    }
    
    const unidadesList = Array.from(new Set(
      unidadesRaw.map((u: any) => String(u.unidade || '').trim()).filter(Boolean)
    ));
    
    if (unidadesList.length === 0) {
      return NextResponse.json({
        ok: true,
        unidades: [],
        ano,
        message: 'Nenhuma unidade encontrada para esta regional',
      });
    }

    // Busca kits de stg_epi_map (mesma fonte do botão "Entregar") - COM PCG
    let kitRows: any[] = [];
    try {
      kitRows = await prisma.$queryRawUnsafe<any[]>(`
        SELECT
          COALESCE(codigo_alterdata::text, '') AS pcg,
          COALESCE(alterdata_funcao::text, '') AS funcao,
          COALESCE(nome_site::text, '') AS site,
          COALESCE(unidade_hospitalar::text, '') AS unidade_hosp,
          COALESCE(epi_item::text, '') AS item,
          COALESCE(quantidade::numeric, 1) AS qtd
        FROM stg_epi_map
      `);
      console.log(`[Diagnóstico] Kits encontrados em stg_epi_map: ${kitRows.length}`);
    } catch (mapError: any) {
      console.error('[Diagnóstico] Erro ao buscar de stg_epi_map:', mapError?.message || mapError);
      return NextResponse.json({
        ok: false,
        error: `Erro ao buscar kits: ${String(mapError)}`,
        unidades: [],
      });
    }

    // Garante tabela de entregas
    await prisma.$executeRawUnsafe(`
      CREATE TABLE IF NOT EXISTS epi_entregas (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        cpf TEXT NOT NULL,
        item TEXT NOT NULL,
        qty_required INT DEFAULT 1,
        qty_delivered INT DEFAULT 0,
        deliveries JSONB DEFAULT '[]',
        created_at TIMESTAMPTZ DEFAULT now(),
        updated_at TIMESTAMPTZ DEFAULT now(),
        UNIQUE(cpf, item)
      );
    `);

    // Busca todas as entregas de uma vez (otimização de performance)
    const todasEntregas = await prisma.$queryRawUnsafe<any[]>(`
      SELECT cpf, item, deliveries
      FROM epi_entregas
    `).catch(() => []);

    // Para cada unidade, calcula meta e entregas por mês
    const unidades: Array<{
      unidade: string;
      qtePrevista: number;
      meses: Record<string, number>;
      totalRealizada: number;
    }> = [];

    for (const unidadeNome of unidadesList) {
      // Busca CPFs da unidade
      const cpfsSql = `
        SELECT DISTINCT COALESCE(a.cpf, '') AS cpf
        FROM stg_alterdata_v2 a
        LEFT JOIN stg_unid_reg u ON UPPER(TRIM(COALESCE(a.unidade_hospitalar, ''))) = UPPER(TRIM(COALESCE(u.nmdepartamento, '')))
        WHERE (UPPER(TRIM(COALESCE(u.nmdepartamento, a.unidade_hospitalar, ''))) = UPPER(TRIM('${unidadeNome.replace(/'/g, "''")}')) 
               OR UPPER(TRIM(a.unidade_hospitalar)) = UPPER(TRIM('${unidadeNome.replace(/'/g, "''")}')))
          AND (a.demissao IS NULL OR a.demissao = '' OR TRIM(a.demissao) = '' OR a.demissao::text >= '${DEMISSAO_LIMITE}')
      `;

      let cpfsRaw: any[] = [];
      try {
        cpfsRaw = await prisma.$queryRawUnsafe<any[]>(cpfsSql);
      } catch (cpfError) {
        console.error(`Erro ao buscar CPFs da unidade ${unidadeNome}:`, cpfError);
        continue; // Pula esta unidade se der erro
      }
      
      const cpfs = cpfsRaw.map((c: any) => String(c.cpf || '').replace(/\D/g, '').slice(-11)).filter(Boolean);

      if (cpfs.length === 0) continue;

      // Calcula meta (Qte Prevista) - soma de EPIs obrigatórios
      // IMPORTANTE: NÃO agrupa por CPF - se CPF aparece 2x (demitido e voltou em 2026), conta 2x
      let qtePrevista = 0;
      
      // Busca TODOS os colaboradores da unidade (sem GROUP BY - mantém duplicatas se houver)
      const colaboradoresSql = `
        SELECT 
          COALESCE(a.cpf, '') AS cpf,
          COALESCE(a.funcao, '') AS funcao,
          COALESCE(a.unidade_hospitalar, '') AS unidade_hospitalar
        FROM stg_alterdata_v2 a
        LEFT JOIN stg_unid_reg u ON UPPER(TRIM(COALESCE(a.unidade_hospitalar, ''))) = UPPER(TRIM(COALESCE(u.nmdepartamento, '')))
        WHERE (UPPER(TRIM(COALESCE(u.nmdepartamento, a.unidade_hospitalar, ''))) = UPPER(TRIM('${unidadeNome.replace(/'/g, "''")}')) 
               OR UPPER(TRIM(a.unidade_hospitalar)) = UPPER(TRIM('${unidadeNome.replace(/'/g, "''")}')))
          AND (a.demissao IS NULL OR a.demissao = '' OR TRIM(a.demissao) = '' OR a.demissao::text >= '${DEMISSAO_LIMITE}')
          AND COALESCE(a.cpf, '') != ''
          AND COALESCE(a.funcao, '') != ''
      `;
      
      let colaboradores: any[] = [];
      try {
        colaboradores = await prisma.$queryRawUnsafe<any[]>(colaboradoresSql);
      } catch (err) {
        console.error(`Erro ao buscar colaboradores da unidade ${unidadeNome}:`, err);
      }
      
      // Funções auxiliares (mesmas do /api/entregas/kit)
      function normKey(s: any): string {
        return (s ?? '').toString().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]/gi, '').toLowerCase();
      }
      
      function normFuncKey(s: any): string {
        const raw = (s ?? '').toString();
        const cleaned = raw.replace(/\(A\)/gi, '').replace(/\s+/g, ' ');
        return normKey(cleaned);
      }
      
      function normUnidKey(s: any): string {
        const raw = (s ?? '').toString().normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase();
        const withoutStops = raw.replace(/\b(hospital|hosp|de|da|das|do|dos)\b/g, ' ');
        return withoutStops.replace(/[^a-z0-9]/gi, '');
      }
      
      // Cache de kits por função+unidade+PCG (para performance)
      const kitCache = new Map<string, number>(); // chave: "funcaoKey|unidadeKey|pcg" -> soma de itens obrigatórios
      
      // Busca PCG da unidade e do fallback
      const UNIDADE_FALLBACK_PCG = 'HOSPITAL DA ILHA';
      let pcgUnidade: string | null = null;
      let pcgHospitalIlha: string | null = null;

      // Busca todas as unidades do mapa para comparar
      let allUnitsList: string[] = [];
      try {
        const allUnits = await prisma.$queryRawUnsafe<any[]>(`
          SELECT DISTINCT unidade_hospitalar FROM stg_epi_map WHERE unidade_hospitalar IS NOT NULL
        `);
        allUnitsList = allUnits.map(u => u.unidade_hospitalar);
      } catch (e) {
        console.warn('[Diagnóstico] Erro ao carregar lista de unidades:', e);
      }

      // Busca PCG do HOSPITAL DA ILHA (sempre necessário para fallback)
      try {
        const fallbackUnit = findBestUnitMatch(UNIDADE_FALLBACK_PCG, allUnitsList);
        if (fallbackUnit) {
          const fallbackResult: any[] = await prisma.$queryRawUnsafe(`
            SELECT DISTINCT COALESCE(codigo_alterdata::text, '') AS pcg
            FROM stg_epi_map
            WHERE UPPER(TRIM(COALESCE(unidade_hospitalar, ''))) = UPPER(TRIM('${fallbackUnit.replace(/'/g, "''")}'))
              AND COALESCE(codigo_alterdata, '') != ''
            LIMIT 1
          `);
          if (fallbackResult.length > 0 && fallbackResult[0].pcg) {
            pcgHospitalIlha = String(fallbackResult[0].pcg).trim();
          }
        }
      } catch (e) {
        console.warn(`[Diagnóstico] Erro ao buscar PCG de ${UNIDADE_FALLBACK_PCG}:`, e);
      }

      if (unidadeNome) {
        try {
          const matchedUnit = findBestUnitMatch(unidadeNome, allUnitsList);
          if (matchedUnit) {
            const pcgResult: any[] = await prisma.$queryRawUnsafe(`
              SELECT DISTINCT COALESCE(codigo_alterdata::text, '') AS pcg
              FROM stg_epi_map
              WHERE UPPER(TRIM(COALESCE(unidade_hospitalar, ''))) = UPPER(TRIM('${matchedUnit.replace(/'/g, "''")}'))
                AND COALESCE(codigo_alterdata, '') != ''
              LIMIT 1
            `);
            if (pcgResult.length > 0 && pcgResult[0].pcg) {
              pcgUnidade = String(pcgResult[0].pcg).trim();
              console.log(`[Diagnóstico] PCG encontrado para unidade ${unidadeNome} (via ${matchedUnit}): ${pcgUnidade}`);
            }
          } else {
            console.warn(`[Diagnóstico] Nenhuma unidade correspondente no banco para: "${unidadeNome}"`);
          }
        } catch (pcgError) {
          console.warn(`[Diagnóstico] Erro ao buscar PCG da unidade ${unidadeNome}:`, pcgError);
        }
      }
      
      const targetPcg = pcgUnidade || pcgHospitalIlha;
      
      // Para cada colaborador (mesmo CPF pode aparecer 2x)
      for (const colab of colaboradores) {
        const funcao = String(colab.funcao || '').trim();
        const unidadeHosp = String(colab.unidade_hospitalar || '').trim();
        
        if (!funcao) continue;
        
        const funcKey = normFuncKey(funcao);
        const unidadeKey = normUnidKey(unidadeHosp);
        const cacheKey = `${funcKey}|${unidadeKey}|${targetPcg || 'null'}`;
        
        // Busca soma do kit (usa cache)
        let somaKit = 0;
        if (kitCache.has(cacheKey)) {
          somaKit = kitCache.get(cacheKey)!;
        } else {
          // Busca kit da função considerando PCG (mesma lógica do /api/entregas/kit)
          // Prioridade 1: Função + PCG alvo + unidade específica
          const porUnidadeComPcg: Array<{ item: string; qtd: number }> = [];
          // Prioridade 2: Função + PCG alvo (genérico do PCG)
          const porPcgGenerico: Array<{ item: string; qtd: number }> = [];
          // Prioridade 3: Função + PCG Hospital da Ilha (fallback)
          const porPcgFallback: Array<{ item: string; qtd: number }> = [];
          
          for (const r of kitRows) {
            const rFuncKey = normFuncKey(r.funcao);
            if (rFuncKey !== funcKey) continue;
            
            const item = String(r.item || '').trim();
            if (!item || !isEpiObrigatorio(item)) continue; // Apenas obrigatórios
            
            const qtd = Number(r.qtd || 1) || 1;
            const pcg = String(r.pcg || '').trim();
            const site = String(r.site || '').trim();
            const unidadeHospMap = String(r.unidade_hosp || '').trim();
            const siteKey = site ? normUnidKey(site) : '';
            const unidadeHospKey = unidadeHospMap ? normUnidKey(unidadeHospMap) : '';
            
            const itemData = { item, qtd };
            
            // Prioridade 1: PCG alvo + unidade específica
            if (targetPcg && pcg === targetPcg && unidadeKey && (siteKey === unidadeKey || unidadeHospKey === unidadeKey)) {
              porUnidadeComPcg.push(itemData);
            }
            // Prioridade 2: PCG alvo (genérico)
            else if (targetPcg && pcg === targetPcg) {
              porPcgGenerico.push(itemData);
            }
            // Prioridade 3: PCG Hospital da Ilha (fallback)
            else if (pcgHospitalIlha && pcg === pcgHospitalIlha && pcg !== targetPcg) {
              porPcgFallback.push(itemData);
            }
          }
          
          // Escolhe a fonte conforme prioridade
          let fonte: Array<{ item: string; qtd: number }> = [];
          if (porUnidadeComPcg.length > 0) {
            fonte = porUnidadeComPcg;
          } else if (porPcgGenerico.length > 0) {
            fonte = porPcgGenerico;
          } else if (porPcgFallback.length > 0) {
            fonte = porPcgFallback;
          }
          
          // Remove duplicatas de item (pega maior quantidade)
          const byItem = new Map<string, number>();
          for (const itemData of fonte) {
            const itemKey = normKey(itemData.item);
            const existing = byItem.get(itemKey);
            if (!existing || itemData.qtd > existing) {
              byItem.set(itemKey, itemData.qtd);
            }
          }
          
          // Soma todos os itens obrigatórios do kit
          somaKit = Array.from(byItem.values()).reduce((acc, qtd) => acc + qtd, 0);
          kitCache.set(cacheKey, somaKit);
        }
        
        // Adiciona à meta (conta cada linha, mesmo se CPF duplicado)
        qtePrevista += somaKit;
      }
      
      console.log(`[Diagnóstico] Unidade ${unidadeNome}: ${colaboradores.length} colaboradores (pode ter CPFs duplicados), meta = ${qtePrevista} itens`);

      // Filtra entregas da unidade (já carregadas acima)
      const entregas = todasEntregas.filter((e: any) => {
        const eCpf = String(e.cpf || '').replace(/\D/g, '').slice(-11);
        return cpfs.includes(eCpf);
      });

      // Inicializa meses
      const meses: Record<string, number> = {};
      for (let m = 1; m <= 12; m++) {
        meses[String(m).padStart(2, '0')] = 0;
      }

      // Processa entregas por mês (apenas obrigatórios)
      // IMPORTANTE: Soma apenas EPIs obrigatórios entregues, baseado no campo deliveries JSONB
      for (const entrega of entregas) {
        const item = String(entrega.item || '').trim();
        if (!item || !isEpiObrigatorio(item)) continue; // Apenas obrigatórios contam

        const deliveries = Array.isArray(entrega.deliveries) ? entrega.deliveries : [];
        
        for (const del of deliveries) {
          if (!del.date || !del.qty) continue;
          
          const dateStr = String(del.date).substring(0, 10);
          const [year, month] = dateStr.split('-');
          
          // Valida formato de data
          if (!year || !month || year.length !== 4 || month.length !== 2) continue;
          
          if (parseInt(year, 10) === ano) {
            const mesKey = month.padStart(2, '0');
            const qty = Number(del.qty || 0);
            if (qty > 0) {
              meses[mesKey] = (meses[mesKey] || 0) + qty;
            }
          }
        }
      }

      const totalRealizada = Object.values(meses).reduce((acc, val) => acc + val, 0);

      unidades.push({
        unidade: unidadeNome,
        qtePrevista,
        meses,
        totalRealizada,
      });
    }

    // Ordena por nome da unidade
    unidades.sort((a, b) => a.unidade.localeCompare(b.unidade));

    return NextResponse.json({
      ok: true,
      unidades,
      ano,
    });
  } catch (e: any) {
    console.error('Erro ao calcular diagnóstico por unidade:', e);
    return NextResponse.json({
      ok: false,
      error: String(e?.message || e),
      unidades: [],
    });
  }
}
