export const dynamic = 'force-dynamic';
import { NextResponse } from "next/server";
import prisma from '@/lib/prisma';

async function ensureTables() {
  // Garante que a tabela epi_entregas existe e está persistente no Neon
  // Esta tabela armazena todas as entregas de EPIs e NÃO deve ser perdida
  // IMPORTANTE (Neon/Vercel): não pode enviar múltiplos comandos no mesmo statement preparado.
  await prisma.$executeRawUnsafe(`
    CREATE TABLE IF NOT EXISTS epi_entregas (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      cpf TEXT NOT NULL,
      item TEXT NOT NULL,
      qty_required INT DEFAULT 1,
      qty_delivered INT DEFAULT 0,
      deliveries JSONB DEFAULT '[]',
      created_at TIMESTAMPTZ DEFAULT now(),
      updated_at TIMESTAMPTZ DEFAULT now(),
      UNIQUE(cpf, item)
    );
  `);

  // Garante índices para performance
  await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS idx_epi_entregas_cpf ON epi_entregas(cpf);`);
  await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS idx_epi_entregas_updated_at ON epi_entregas(updated_at);`);
}

export async function GET(req: Request) {
  try {
    await ensureTables();
    const { searchParams } = new URL(req.url);
    const cpf = String(searchParams.get("cpf") || "");
    if (!cpf) return NextResponse.json({ ok: false, error: "cpf obrigatório" }, { status: 200 });
    // Evita BigInt no JSON (id é BIGINT no Postgres)
    const rows = await prisma.$queryRawUnsafe<any[]>(`
      select
        id::text as id,
        cpf,
        item,
        qty_required,
        qty_delivered,
        deliveries,
        created_at,
        updated_at
      from epi_entregas
      where cpf = $1
    `, cpf);
    return NextResponse.json({ ok: true, rows });
  } catch (e: any) {
    return NextResponse.json({ ok: false, error: String(e?.message||e) }, { status: 200 });
  }
}

export async function POST(req: Request) {
  try {
    await ensureTables();
    const body = await req.json();
    const cpf = String(body?.cpf || "").replace(/\D/g,'');
    
    if (!cpf) return NextResponse.json({ ok: false, error: "cpf é obrigatório" }, { status: 200 });

    // Suporte para entrega em massa (array de itens)
    if (Array.isArray(body?.items) && body.items.length > 0) {
      const results: any[] = [];
      
      for (const itemData of body.items) {
        const item = String(itemData?.item || "");
        const qty = Number(itemData?.qty ?? 1);
        const date = String(itemData?.date || "").substring(0,10) || new Date().toISOString().substring(0,10);
        const required = Number(itemData?.qty_required ?? 1) || 1;

        if (!item || qty <= 0) continue;
        // Bloqueia datas fora do período (evita 31/12/2024 etc)
        if (date && /^\d{4}-\d{2}-\d{2}$/.test(date)) {
          const year = parseInt(date.slice(0, 4), 10);
          if (year < 2026) {
            console.warn(`[deliver] Ignorando lançamento com data antiga (${date}) para item ${item}`);
            continue;
          }
        }

        try {
          const up = await prisma.$queryRawUnsafe<any[]>(`
            INSERT INTO epi_entregas (cpf, item, qty_required, qty_delivered, deliveries)
            VALUES (
              $1, $2, $3,
              LEAST($3, $4),
              jsonb_build_array(jsonb_build_object('date', $5, 'qty', LEAST($3, $6)))
            )
            ON CONFLICT (cpf, item) DO UPDATE SET
              qty_required = EXCLUDED.qty_required,
              qty_delivered = LEAST(EXCLUDED.qty_required, epi_entregas.qty_delivered + $6),
              deliveries = CASE
                WHEN epi_entregas.qty_delivered >= EXCLUDED.qty_required THEN epi_entregas.deliveries
                ELSE epi_entregas.deliveries || jsonb_build_array(
                  jsonb_build_object('date', $5, 'qty', LEAST(EXCLUDED.qty_required - epi_entregas.qty_delivered, $6))
                )
              END,
              updated_at = now()
            RETURNING
              id::text as id,
              cpf,
              item,
              qty_required,
              qty_delivered,
              deliveries,
              created_at,
              updated_at;
          `, cpf, item, required, qty, date, qty);
          
          if (up && up[0]) {
            results.push(up[0]);
          }
        } catch (itemError: any) {
          console.error(`Erro ao processar item ${item}:`, itemError);
          // Continua processando os outros itens
        }
      }

      return NextResponse.json({ 
        ok: true, 
        rows: results,
        count: results.length,
        message: `${results.length} item(ns) processado(s) com sucesso`
      });
    }

    // Modo antigo: entrega individual (compatibilidade)
    const item = String(body?.item || "");
    const qty = Number(body?.qty ?? 1);
    const date = String(body?.date || "").substring(0,10) || new Date().toISOString().substring(0,10);
    const required = Number(body?.qty_required ?? 1) || 1;

    if (!item) return NextResponse.json({ ok: false, error: "item é obrigatório" }, { status: 200 });
    if (date && /^\d{4}-\d{2}-\d{2}$/.test(date)) {
      const year = parseInt(date.slice(0, 4), 10);
      if (year < 2026) {
        return NextResponse.json({ ok: false, error: `Data inválida para entrega: ${date}` }, { status: 200 });
      }
    }

    const up = await prisma.$queryRawUnsafe<any[]>(`
      INSERT INTO epi_entregas (cpf, item, qty_required, qty_delivered, deliveries)
      VALUES (
        $1, $2, $3,
        LEAST($3, $4),
        jsonb_build_array(jsonb_build_object('date', $5, 'qty', LEAST($3, $6)))
      )
      ON CONFLICT (cpf, item) DO UPDATE SET
        qty_required = EXCLUDED.qty_required,
        qty_delivered = LEAST(EXCLUDED.qty_required, epi_entregas.qty_delivered + $6),
        deliveries = CASE
          WHEN epi_entregas.qty_delivered >= EXCLUDED.qty_required THEN epi_entregas.deliveries
          ELSE epi_entregas.deliveries || jsonb_build_array(
            jsonb_build_object('date', $5, 'qty', LEAST(EXCLUDED.qty_required - epi_entregas.qty_delivered, $6))
          )
        END,
        updated_at = now()
      RETURNING
        id::text as id,
        cpf,
        item,
        qty_required,
        qty_delivered,
        deliveries,
        created_at,
        updated_at;
    `, cpf, item, required, qty, date, qty);
    return NextResponse.json({ ok: true, row: up?.[0] ?? null });
  } catch (e: any) {
    return NextResponse.json({ ok: false, error: String(e?.message||e) }, { status: 200 });
  }
}

export async function PUT(req: Request) {
  try {
    await ensureTables();
    const body = await req.json().catch(() => ({}));

    const cpf = String(body?.cpf || '').replace(/\D/g, '');
    const item = String(body?.item || '').trim();
    const required = Math.max(1, Number(body?.qty_required ?? 1) || 1);
    const deliveriesIn = Array.isArray(body?.deliveries) ? body.deliveries : [];

    if (!cpf) return NextResponse.json({ ok: false, error: 'cpf é obrigatório' }, { status: 200 });
    if (!item) return NextResponse.json({ ok: false, error: 'item é obrigatório' }, { status: 200 });

    // Normaliza/valida lançamentos (somente 2026+)
    const deliveries = deliveriesIn
      .map((d: any) => ({
        date: String(d?.date || '').substring(0, 10),
        qty: Number(d?.qty ?? 0),
      }))
      .filter((d: any) => /^\d{4}-\d{2}-\d{2}$/.test(d.date))
      .filter((d: any) => Number.isFinite(d.qty) && d.qty > 0)
      .filter((d: any) => parseInt(d.date.slice(0, 4), 10) >= 2026);

    const sum = deliveries.reduce((acc: number, d: any) => acc + Number(d.qty || 0), 0);
    const qtyDelivered = Math.min(required, sum);

    const up = await prisma.$queryRawUnsafe<any[]>(`
      INSERT INTO epi_entregas (cpf, item, qty_required, qty_delivered, deliveries)
      VALUES ($1, $2, $3, $4, $5::jsonb)
      ON CONFLICT (cpf, item) DO UPDATE SET
        qty_required = EXCLUDED.qty_required,
        qty_delivered = EXCLUDED.qty_delivered,
        deliveries = EXCLUDED.deliveries,
        updated_at = now()
      RETURNING
        id::text as id,
        cpf,
        item,
        qty_required,
        qty_delivered,
        deliveries,
        created_at,
        updated_at;
    `, cpf, item, required, qtyDelivered, JSON.stringify(deliveries));

    return NextResponse.json({ ok: true, row: up?.[0] ?? null });
  } catch (e: any) {
    return NextResponse.json({ ok: false, error: String(e?.message || e) }, { status: 200 });
  }
}
