export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

import { NextResponse } from 'next/server';
import prisma from '@/lib/prisma';
import { isEpiObrigatorio } from '@/data/epiObrigatorio';

/**
 * Calcula o progresso de entregas por mês
 * Retorna quantos EPIs obrigatórios foram entregues em cada mês
 */
export async function GET(req: Request) {
  try {
    const url = new URL(req.url);
    const regional = url.searchParams.get('regional') || '';
    const unidade = url.searchParams.get('unidade') || '';
    const ano = parseInt(url.searchParams.get('ano') || '2026', 10);

    if (!regional) {
      return NextResponse.json({ 
        ok: false, 
        error: 'Regional é obrigatória',
        meses: {}
      });
    }

    // Inicializa objeto com todos os meses zerados
    const meses: Record<string, number> = {};
    for (let m = 1; m <= 12; m++) {
      meses[String(m).padStart(2, '0')] = 0;
    }

    // Busca CPFs dos colaboradores da regional/unidade
    const wh: string[] = [];
    const regTrim = regional.trim();
    const uniTrim = unidade.trim();

    const hasUnidReg: any[] = await prisma.$queryRawUnsafe(`
      SELECT EXISTS (
        SELECT 1 FROM pg_catalog.pg_class c
        JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
        WHERE c.relkind IN ('r','v','m') AND n.nspname = 'public' AND c.relname = 'stg_unid_reg'
      ) AS exists
    `);
    const useJoin = hasUnidReg?.[0]?.exists;

    if (regTrim && useJoin) {
      wh.push(`(UPPER(TRIM(COALESCE(u.regional_responsavel, ''))) = UPPER(TRIM('${regTrim.replace(/'/g, "''")}')) OR UPPER(TRIM(COALESCE(a.unidade_hospitalar, ''))) IN (
        SELECT UPPER(TRIM(nmdepartamento)) FROM stg_unid_reg WHERE UPPER(TRIM(regional_responsavel)) = UPPER(TRIM('${regTrim.replace(/'/g, "''")}'))
      ))`);
    }
    
    if (uniTrim) {
      if (useJoin) {
        wh.push(`(UPPER(TRIM(COALESCE(u.nmdepartamento, a.unidade_hospitalar, ''))) = UPPER(TRIM('${uniTrim.replace(/'/g, "''")}')) OR UPPER(TRIM(a.unidade_hospitalar)) = UPPER(TRIM('${uniTrim.replace(/'/g, "''")}')))`);
      } else {
        wh.push(`UPPER(TRIM(COALESCE(a.unidade_hospitalar, ''))) = UPPER(TRIM('${uniTrim.replace(/'/g, "''")}'))`);
      }
    }

    const DEMISSAO_ANO_MINIMO = 2026;
    wh.push(`(
      a.demissao IS NULL
      OR a.demissao = ''
      OR TRIM(a.demissao) = ''
      OR (
        CASE
          WHEN TRIM(a.demissao) ~ '^\\d+$' THEN (DATE '1899-12-30' + (TRIM(a.demissao)::int))
          WHEN TRIM(a.demissao) ~ '^\\d{4}-\\d{2}-\\d{2}' THEN SUBSTRING(TRIM(a.demissao), 1, 10)::date
          WHEN TRIM(a.demissao) ~ '^\\d{2}/\\d{2}/\\d{4}' THEN to_date(SUBSTRING(TRIM(a.demissao), 1, 10), 'DD/MM/YYYY')
          ELSE NULL
        END
      ) IS NOT NULL
      AND EXTRACT(YEAR FROM (
        CASE
          WHEN TRIM(a.demissao) ~ '^\\d+$' THEN (DATE '1899-12-30' + (TRIM(a.demissao)::int))
          WHEN TRIM(a.demissao) ~ '^\\d{4}-\\d{2}-\\d{2}' THEN SUBSTRING(TRIM(a.demissao), 1, 10)::date
          WHEN TRIM(a.demissao) ~ '^\\d{2}/\\d{2}/\\d{4}' THEN to_date(SUBSTRING(TRIM(a.demissao), 1, 10), 'DD/MM/YYYY')
          ELSE NULL
        END
      ))::int >= ${DEMISSAO_ANO_MINIMO}
    )`);

    const whereSql = wh.length ? `WHERE ${wh.join(' AND ')}` : '';

    const sql = useJoin ? `
      SELECT DISTINCT COALESCE(a.cpf, '') AS cpf
      FROM stg_alterdata_v2 a
      LEFT JOIN stg_unid_reg u ON UPPER(TRIM(COALESCE(a.unidade_hospitalar, ''))) = UPPER(TRIM(COALESCE(u.nmdepartamento, '')))
      ${whereSql}
    ` : `
      SELECT DISTINCT COALESCE(a.cpf, '') AS cpf
      FROM stg_alterdata_v2 a
      ${whereSql}
    `;

    const colaboradores = await prisma.$queryRawUnsafe<any[]>(sql);
    const cpfs = colaboradores.map((c: any) => String(c.cpf || '').replace(/\D/g, '').slice(-11)).filter(Boolean);

    if (cpfs.length === 0) {
      return NextResponse.json({
        ok: true,
        meses,
        total: 0,
      });
    }

    // Busca entregas de EPIs obrigatórios
    await prisma.$executeRawUnsafe(`
      CREATE TABLE IF NOT EXISTS epi_entregas (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        cpf TEXT NOT NULL,
        item TEXT NOT NULL,
        qty_required INT DEFAULT 1,
        qty_delivered INT DEFAULT 0,
        deliveries JSONB DEFAULT '[]',
        created_at TIMESTAMPTZ DEFAULT now(),
        updated_at TIMESTAMPTZ DEFAULT now(),
        UNIQUE(cpf, item)
      );
    `);

    // Busca todas as entregas dos colaboradores (CPF normalizado: só dígitos)
    // IN explícito evita problema de passagem de array no Prisma e garante match com qualquer formato de CPF na tabela
    const cpfList = cpfs.map((c) => `'${String(c).replace(/'/g, "''")}'`).join(',');
    const entregas = await prisma.$queryRawUnsafe<any[]>(`
      SELECT cpf, item, deliveries, qty_delivered,
             updated_at::text AS updated_at, created_at::text AS created_at
      FROM epi_entregas
      WHERE regexp_replace(COALESCE(TRIM(cpf), ''), '[^0-9]', '', 'g') IN (${cpfList})
    `);

    // Processa entregas por mês (apenas EPIs obrigatórios)
    for (const entrega of entregas) {
      const item = String(entrega.item || '').trim();
      if (!item || !isEpiObrigatorio(item)) continue;

      const deliveries = Array.isArray(entrega.deliveries) ? entrega.deliveries : [];
      let contadoNoArray = 0;

      for (const del of deliveries) {
        if (!del.date || !del.qty) continue;
        const dateStr = String(del.date).substring(0, 10);
        const [year, month] = dateStr.split('-');
        if (parseInt(year, 10) === ano) {
          const mesKey = (month || '').padStart(2, '0');
          const q = Number(del.qty || 0);
          meses[mesKey] = (meses[mesKey] || 0) + q;
          contadoNoArray += q;
        }
      }

      // Quando qty_delivered > 0 mas deliveries vazio ou sem data no ano, conta pelo updated_at (evita realizado zerado)
      const qtyDelivered = Number(entrega.qty_delivered || 0);
      if (qtyDelivered > 0 && contadoNoArray < qtyDelivered) {
        const falta = qtyDelivered - contadoNoArray;
        const dtStr = (entrega.updated_at || entrega.created_at || '').toString().substring(0, 10);
        if (/^\d{4}-\d{2}-\d{2}$/.test(dtStr)) {
          const [y, m] = dtStr.split('-');
          if (parseInt(y, 10) === ano) {
            const mesKey = (m || '').padStart(2, '0');
            meses[mesKey] = (meses[mesKey] || 0) + falta;
          }
        }
      }
    }

    const total = Object.values(meses).reduce((acc, val) => acc + val, 0);

    return NextResponse.json({
      ok: true,
      meses,
      total,
      ano,
    });
  } catch (e: any) {
    console.error('Erro ao calcular progresso:', e);
    return NextResponse.json({
      ok: false,
      error: String(e?.message || e),
      meses: {},
      total: 0,
    });
  }
}
