export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

import { NextResponse } from 'next/server';
import prisma from '@/lib/prisma';
import { getValidadeMeses } from '@/data/epiValidade';

type Alerta = {
  cpf: string;
  nome: string;
  item: string;
  ultima_entrega_em: string;
  proxima_entrega_em: string;
  meses_validade: number;
  vencida: boolean;
  dias_vencido: number;
};

function addMonths(dateStr: string, months: number): string {
  const d = new Date(dateStr);
  d.setUTCMonth(d.getUTCMonth() + months);
  return d.toISOString().slice(0, 10);
}

function diasEntre(a: string, b: string): number {
  const t = new Date(b).getTime() - new Date(a).getTime();
  return Math.floor(t / (24 * 60 * 60 * 1000));
}

export async function GET(req: Request) {
  try {
    const { searchParams } = new URL(req.url);
    const regional = (searchParams.get('regional') || '').trim();
    const unidade = (searchParams.get('unidade') || '').trim();

    // Garante que epi_entregas existe
    await prisma.$executeRawUnsafe(`
      CREATE TABLE IF NOT EXISTS epi_entregas (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        cpf TEXT NOT NULL,
        item TEXT NOT NULL,
        qty_required INT DEFAULT 1,
        qty_delivered INT DEFAULT 0,
        deliveries JSONB DEFAULT '[]',
        created_at TIMESTAMPTZ DEFAULT now(),
        updated_at TIMESTAMPTZ DEFAULT now(),
        UNIQUE(cpf, item)
      );
    `);

    let cpfs: string[] = [];
    if (regional) {
      try {
        const regEscaped = regional.replace(/'/g, "''");
        const hasUnidReg: any[] = await prisma.$queryRawUnsafe(`
          SELECT EXISTS (
            SELECT 1 FROM pg_catalog.pg_class c
            JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relkind IN ('r','v','m') AND n.nspname = 'public' AND c.relname = 'stg_unid_reg'
          ) AS exists
        `);
        const useJoin = hasUnidReg?.[0]?.exists;
        if (useJoin) {
          const wh = [`UPPER(TRIM(COALESCE(u.regional_responsavel, ''))) = UPPER(TRIM('${regEscaped}'))`];
          if (unidade) {
            wh.push(`(UPPER(TRIM(COALESCE(u.nmdepartamento, a.unidade_hospitalar, ''))) = UPPER(TRIM('${unidade.replace(/'/g, "''")}')) OR UPPER(TRIM(a.unidade_hospitalar)) = UPPER(TRIM('${unidade.replace(/'/g, "''")}'))`);
          }
          const sql = `
            SELECT DISTINCT COALESCE(a.cpf, '') AS cpf
            FROM stg_alterdata_v2 a
            LEFT JOIN stg_unid_reg u ON UPPER(TRIM(COALESCE(a.unidade_hospitalar, ''))) = UPPER(TRIM(COALESCE(u.nmdepartamento, '')))
            WHERE ${wh.join(' AND ')}
          `;
          const rows: any[] = await prisma.$queryRawUnsafe(sql);
          cpfs = rows.map((r: any) => String(r.cpf || '').replace(/\D/g, '').slice(-11)).filter(Boolean);
        } else {
          const rows: any[] = await prisma.$queryRawUnsafe(
            `SELECT DISTINCT cpf FROM stg_alterdata_v2 WHERE UPPER(TRIM(COALESCE(unidade_hospitalar, ''))) != ''`,
          );
          cpfs = rows.map((r: any) => String(r.cpf || '').replace(/\D/g, '').slice(-11)).filter(Boolean);
        }
      } catch (_) {
        cpfs = [];
      }
    }

    const hoje = new Date().toISOString().slice(0, 10);
    const whereCpf = cpfs.length > 0 ? `AND cpf = ANY($1::text[])` : '';
    const params = cpfs.length > 0 ? [cpfs] : [];
    const rows: any[] = await prisma.$queryRawUnsafe<any[]>(
      `SELECT id::text, cpf, item, deliveries FROM epi_entregas WHERE deliveries IS NOT NULL AND jsonb_array_length(deliveries) > 0 ${whereCpf}`,
      ...params,
    );

    const alertas: Alerta[] = [];
    for (const row of rows) {
      const deliveries = Array.isArray(row.deliveries) ? row.deliveries : [];
      if (deliveries.length === 0) continue;
      const last = deliveries.reduce((prev: any, cur: any) => {
        const d = String(cur?.date || '').slice(0, 10);
        return (!prev || d > (prev.date || '')) ? { ...cur, date: d } : prev;
      }, null);
      if (!last || !last.date) continue;
      const meses = getValidadeMeses(row.item);
      const proxima = addMonths(last.date, meses);
      const vencida = proxima < hoje;
      if (!vencida) continue;
      alertas.push({
        cpf: String(row.cpf || ''),
        nome: '',
        item: String(row.item || ''),
        ultima_entrega_em: last.date,
        proxima_entrega_em: proxima,
        meses_validade: meses,
        vencida: true,
        dias_vencido: diasEntre(proxima, hoje),
      });
    }

    const cpfsUnicos = [...new Set(alertas.map((a) => a.cpf))];
    let nomesMap: Record<string, string> = {};
    if (cpfsUnicos.length > 0) {
      try {
        const nomesRows: any[] = await prisma.$queryRawUnsafe(
          `SELECT DISTINCT ON (cpf) cpf, COALESCE(colaborador, '') AS nome FROM stg_alterdata_v2 WHERE cpf = ANY($1::text[])`,
          cpfsUnicos,
        );
        for (const r of nomesRows) {
          nomesMap[String(r.cpf || '').replace(/\D/g, '').slice(-11)] = String(r.nome || '');
        }
      } catch (_) {}
    }

    for (const a of alertas) {
      const key = a.cpf.replace(/\D/g, '').slice(-11);
      a.nome = nomesMap[key] || a.cpf;
    }

    return NextResponse.json({
      ok: true,
      alertas: alertas.sort((x, y) => x.dias_vencido - y.dias_vencido),
      total: alertas.length,
    });
  } catch (e: any) {
    console.error('[alertas-vencidas]', e);
    return NextResponse.json({ ok: false, error: String(e?.message || e), alertas: [], total: 0 });
  }
}
